name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install node dependencies
        run: |
          npm i
          npx playwright install chromium

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate

      - name: Run script to generate CSV and screenshots
        run: npm test

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        id: upload-screenshots
        with:
          name: screenshots
          path: screenshots/

      - name: Upload CSV as an artifact
        uses: actions/upload-artifact@v4
        id: upload-csv
        with:
          name: csv-data
          path: website_theme_support.csv

      - name: Update README
        run: |
          python -c "import pandas as pd
          df = pd.read_csv('./website_theme_support.csv')
          markdown_table = df.to_markdown(index=False)
          data_table = '## Test Results (Auto generated)\n\n' + markdown_table
          screenshots_section = '## Screenshots\n\nScreenshots available [here](${{ steps.upload-screenshots.outputs.artifact-url }}).'
          full_insert = data_table + '\n' + screenshots_section

          with open('README.md', 'r') as f:
              readme_content = f.read()
          start_marker = '<!-- AUTO-GENERATED-CONTENT:START (DO_NOT_REMOVE) -->'
          end_marker = '<!-- AUTO-GENERATED-CONTENT:END -->'
          start_pos = readme_content.find(start_marker) + len(start_marker)
          end_pos = readme_content.find(end_marker)

          updated_readme = readme_content[:start_pos] + '\n' + full_insert + '\n' + readme_content[end_pos:]

          with open('README.md', 'w') as f:
              f.write(updated_readme)
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'Issam Mani'
          git config --global user.email 'issamouu69@gmail.com'
          git add README.md
          git commit -m 'Update README with latest data and screenshots'
          git push
